# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('ministry_department', models.CharField(max_length=150)),
                ('state_department', models.CharField(max_length=150)),
                ('data_sets_actual_count', models.IntegerField(default=0)),
                ('data_sets_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('node', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Catalog')),
            ],
        ),
    ]
