# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ministry_department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='state_department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
